Remaining reviews on my votes buttons
nicmarti/cfp-devoxx pull request #207
Opened 2020-01-13 13:55 UTC by fcamblor

Displaying remaining reviews on my votes screen (+ trophy badge when `remainingReviews = 0`), as suggested by @aheritier on #206

![All_my_votes_-_Devoxx_France_2020](https://user-images.githubusercontent.com/603815/72261119-882b3400-3614-11ea-98ee-18d77d4a6255.png)

Important : this PR requires #206 (that's why I put my commit as an extension of #206)

2020-01-13 14:11 UTC, aheritier requested changes
For a better readability I would propose to use real bootstrap badges @fcamblor 

![Screenshot 2020-01-13 15 10 36](https://user-images.githubusercontent.com/174600/72262259-e3f6bc80-3616-11ea-854e-20f28ae08037.png)

But I have a bug with real data. Counters aren't the number of reviews to do but the total of proposals

2020-01-13 14:11 UTC, aheritier commented on app/views/CFPAdmin/allMyVotes.scala.html
> +                            (@{proposalNotReviewedCountByType.get(confType.id).getOrElse(0) })
```suggestion
                            <span class="badge badge-pill badge-light">@{proposalNotReviewedCountByType.get(confType.id).getOrElse(0) }</span>
```

2020-01-13 14:11 UTC, aheritier commented on app/views/CFPAdmin/allMyVotes.scala.html
> +                            (@{proposalNotReviewedCountByType.get(talkType).getOrElse(0) })
```suggestion
                            <span class="badge badge-pill badge-light">@{proposalNotReviewedCountByType.get(talkType).getOrElse(0) }</span>
```

2020-01-13 14:11 UTC, aheritier commented on app/views/CFPAdmin/allMyVotes.scala.html
> +                                (@{proposalNotReviewedCountForCurrentTypeByTrack.get(track.id).getOrElse(0) })
```suggestion
                                <span class="badge badge-pill badge-light">@{proposalNotReviewedCountForCurrentTypeByTrack.get(track.id).getOrElse(0) }</span>
```

2020-01-13 14:11 UTC, aheritier commented on app/views/GoldenTicketController/allMyGoldenTicketVotes.scala.html
> +                            (@{proposalNotReviewedCountByType.get(confType.id).getOrElse(0) })
```suggestion
                            <span class="badge badge-pill badge-light">@{proposalNotReviewedCountByType.get(confType.id).getOrElse(0) }</span>
```

2020-01-13 14:11 UTC, aheritier commented on app/views/GoldenTicketController/allMyGoldenTicketVotes.scala.html
> +                            (@{proposalNotReviewedCountByType.get(talkType).getOrElse(0) })
```suggestion
                            <span class="badge badge-pill badge-light">@{proposalNotReviewedCountByType.get(talkType).getOrElse(0) }</span>
```

2020-01-13 14:11 UTC, aheritier commented on app/views/GoldenTicketController/allMyGoldenTicketVotes.scala.html
> +                                (@{proposalNotReviewedCountForCurrentTypeByTrack.get(track.id).getOrElse(0) })
```suggestion
                               <span class="badge badge-pill badge-light">@{proposalNotReviewedCountForCurrentTypeByTrack.get(track.id).getOrElse(0) }</span>
```

2020-01-13 14:18 UTC, fcamblor commented
💯 @aheritier, just pushed the fix 👍

2020-01-13 14:31 UTC, aheritier commented
@fcamblor the fix for badges, but you fixed the issue with the counter values ?

2020-01-13 14:36 UTC, fcamblor commented
> But I have a bug with real data. Counters aren't the number of reviews to do but the total of proposals

Didn't read your message until the end

I think the count is ok at the "Proposal type" level, but not at the "Track" level.
Will look at it

2020-01-13 15:05 UTC, aheritier commented
@fcamblor it's strange because if you look at my screenshot you see that I have 517 conferences to review which is wrong even at the type level !!!!
I have 147 to review (screenshot from prod)

![Screenshot 2020-01-13 16 05 10](https://user-images.githubusercontent.com/174600/72266374-86666e00-361e-11ea-8de4-47365d2364b2.png)

2020-01-13 15:11 UTC, fcamblor commented
Yes I found the problem : I'm not taking the track filter into consideration when displaying those numbers

2020-01-13 15:40 UTC, fcamblor commented
force pushed the fix (twice), should be better now :-)

2020-01-13 15:45 UTC, fcamblor commented
Added a commit fixing some ":" duplicates here and there in filtering labels

2020-01-13 17:28 UTC, aheritier commented
I am testing 

```
* 72f21a95 (HEAD -> pr/207, origin/pr/207, fcamblor/badges-on-my-votes) fixed typo in type/track filtering label (':' displayed twice)
```

But it seems wrong.

In production for universities I have 

> Out of 37 talks, you have reviewed 34 talks and 3 reviews remain.

![Screenshot 2020-01-13 18 22 32](https://user-images.githubusercontent.com/174600/72277198-d3077480-3631-11ea-893b-609903a0ef02.png)

But with the PR

> Out of 71 talks, you have reviewed 34 talks and 37 reviews remain.

![Screenshot 2020-01-13 18 21 31](https://user-images.githubusercontent.com/174600/72277302-fb8f6e80-3631-11ea-92b7-3abd2e478895.png)

Production is right. We received 37 universities, I reviewed 34 and thus I have 3 remaining

In the PR the total (71 = 37 + my 34 reviews :-/ ) instead of 37
the number of reviews (37 = 3 +34 ) instead of 3

2020-01-13 18:05 UTC, fcamblor commented
mmm are you sure about your redis dump/sync with production ?

Not saying that there isn't any bug, but I don't have the same behaviour locally (overall total of reviews seem ok here)

Cannot it be due to a "double import" of proposals (or something like this) ?

Redis commands to check (prefix it with `docker exec -ti cfp-devoxx_redis` if running with docker) :
- To list all proposals keys (check if there isn't any duplicate here for some universities) :
   ```
redis-cli hkeys Proposals
   ```
- To list entries for a given key :
    ```
redis-cli hget Proposals HGE-1930
    ```

Not being a Redis expert but :
- I think that HASHes should not have the same key twice (I don't expect the first command to return duplicates)
- For a given key, you're not supposed to have multiple values (second command), so I don't see how it could happen that you have multiple entries here

I'll triple check once at home but honestly I don't understand what's happening here :(

2020-01-13 18:10 UTC, aheritier commented
if I run `hkeys Proposals` I get 6117 entries thus probably all the keys used for several years cc @nicmarti 
`hget Proposals HGE-1930` gives me one entry

2020-01-13 18:17 UTC, fcamblor commented
my bad I think I got it

2020-01-13 18:24 UTC, fcamblor commented
@aheritier can you try to test again ?

Ugly copy/paste spotted

2020-01-13 19:05 UTC, aheritier approved these changes
it's all good.
it's beautiful and ok to merge

![Screenshot 2020-01-13 20 04 47](https://user-images.githubusercontent.com/174600/72283895-09e48700-3640-11ea-8db9-fde69d7030dc.png)

cc @nicmarti

2020-01-13 20:42 UTC, aheritier commented
@nicmarti merging this Pr will solve #206 too cc @fcamblor

2020-01-14 17:33 UTC, aheritier commented
@nicmarti can you merge/deploy it please ?

2020-01-15 09:50 UTC, merged

2020-01-15 09:51 UTC, nicmarti commented
Thanks for the PR @fcamblor. It should be deployed on clever cloud at 10h55 today